// Major US cities for programmatic SEO - 500+ cities
export const US_MAJOR_CITIES = [
  // California (50+ cities)
  { state: 'ca', city: 'los-angeles', name: 'Los Angeles', population: 3898747 },
  { state: 'ca', city: 'san-diego', name: 'San Diego', population: 1386932 },
  { state: 'ca', city: 'san-jose', name: 'San Jose', population: 1013240 },
  { state: 'ca', city: 'san-francisco', name: 'San Francisco', population: 873965 },
  { state: 'ca', city: 'fresno', name: 'Fresno', population: 542107 },
  { state: 'ca', city: 'sacramento', name: 'Sacramento', population: 513624 },
  { state: 'ca', city: 'long-beach', name: 'Long Beach', population: 466742 },
  { state: 'ca', city: 'oakland', name: 'Oakland', population: 440646 },
  { state: 'ca', city: 'bakersfield', name: 'Bakersfield', population: 384145 },
  { state: 'ca', city: 'anaheim', name: 'Anaheim', population: 346824 },
  { state: 'ca', city: 'santa-ana', name: 'Santa Ana', population: 332318 },
  { state: 'ca', city: 'riverside', name: 'Riverside', population: 331360 },
  { state: 'ca', city: 'stockton', name: 'Stockton', population: 312697 },
  { state: 'ca', city: 'irvine', name: 'Irvine', population: 287401 },
  { state: 'ca', city: 'chula-vista', name: 'Chula Vista', population: 274492 },
  { state: 'ca', city: 'fremont', name: 'Fremont', population: 241110 },
  { state: 'ca', city: 'san-bernardino', name: 'San Bernardino', population: 222101 },
  { state: 'ca', city: 'modesto', name: 'Modesto', population: 218464 },
  { state: 'ca', city: 'fontana', name: 'Fontana', population: 214547 },
  { state: 'ca', city: 'santa-clarita', name: 'Santa Clarita', population: 212979 },
  { state: 'ca', city: 'oxnard', name: 'Oxnard', population: 202063 },
  { state: 'ca', city: 'moreno-valley', name: 'Moreno Valley', population: 213055 },
  { state: 'ca', city: 'glendale', name: 'Glendale', population: 196543 },
  { state: 'ca', city: 'huntington-beach', name: 'Huntington Beach', population: 198711 },
  { state: 'ca', city: 'ontario', name: 'Ontario', population: 185010 },
  { state: 'ca', city: 'rancho-cucamonga', name: 'Rancho Cucamonga', population: 177603 },
  { state: 'ca', city: 'santa-rosa', name: 'Santa Rosa', population: 178127 },
  { state: 'ca', city: 'oceanside', name: 'Oceanside', population: 174648 },
  { state: 'ca', city: 'garden-grove', name: 'Garden Grove', population: 171949 },
  { state: 'ca', city: 'pasadena', name: 'Pasadena', population: 138699 },
  { state: 'ca', city: 'hayward', name: 'Hayward', population: 162954 },
  { state: 'ca', city: 'corona', name: 'Corona', population: 169868 },
  { state: 'ca', city: 'salinas', name: 'Salinas', population: 163542 },
  { state: 'ca', city: 'pomona', name: 'Pomona', population: 151713 },
  { state: 'ca', city: 'escondido', name: 'Escondido', population: 151038 },
  { state: 'ca', city: 'sunnyvale', name: 'Sunnyvale', population: 155805 },
  { state: 'ca', city: 'palmdale', name: 'Palmdale', population: 169450 },
  { state: 'ca', city: 'fullerton', name: 'Fullerton', population: 143617 },
  { state: 'ca', city: 'orange', name: 'Orange', population: 139911 },
  { state: 'ca', city: 'santa-monica', name: 'Santa Monica', population: 91411 },
  { state: 'ca', city: 'beverly-hills', name: 'Beverly Hills', population: 32701 },
  { state: 'ca', city: 'palo-alto', name: 'Palo Alto', population: 68572 },
  { state: 'ca', city: 'mountain-view', name: 'Mountain View', population: 83377 },
  { state: 'ca', city: 'berkeley', name: 'Berkeley', population: 124321 },
  { state: 'ca', city: 'san-mateo', name: 'San Mateo', population: 105661 },
  { state: 'ca', city: 'burbank', name: 'Burbank', population: 107337 },
  { state: 'ca', city: 'torrance', name: 'Torrance', population: 147067 },
  { state: 'ca', city: 'costa-mesa', name: 'Costa Mesa', population: 111918 },
  { state: 'ca', city: 'carlsbad', name: 'Carlsbad', population: 114746 },
  
  // Texas (30+ cities)
  { state: 'tx', city: 'houston', name: 'Houston', population: 2320268 },
  { state: 'tx', city: 'san-antonio', name: 'San Antonio', population: 1547253 },
  { state: 'tx', city: 'dallas', name: 'Dallas', population: 1343573 },
  { state: 'tx', city: 'austin', name: 'Austin', population: 978908 },
  { state: 'tx', city: 'fort-worth', name: 'Fort Worth', population: 909585 },
  { state: 'tx', city: 'el-paso', name: 'El Paso', population: 681728 },
  { state: 'tx', city: 'arlington', name: 'Arlington', population: 398854 },
  { state: 'tx', city: 'corpus-christi', name: 'Corpus Christi', population: 326586 },
  { state: 'tx', city: 'plano', name: 'Plano', population: 287677 },
  { state: 'tx', city: 'laredo', name: 'Laredo', population: 262491 },
  { state: 'tx', city: 'lubbock', name: 'Lubbock', population: 258862 },
  { state: 'tx', city: 'garland', name: 'Garland', population: 239928 },
  { state: 'tx', city: 'irving', name: 'Irving', population: 239798 },
  { state: 'tx', city: 'amarillo', name: 'Amarillo', population: 199371 },
  { state: 'tx', city: 'grand-prairie', name: 'Grand Prairie', population: 194543 },
  { state: 'tx', city: 'brownsville', name: 'Brownsville', population: 183046 },
  { state: 'tx', city: 'pasadena', name: 'Pasadena', population: 151227 },
  { state: 'tx', city: 'mckinney', name: 'McKinney', population: 191645 },
  { state: 'tx', city: 'frisco', name: 'Frisco', population: 200490 },
  { state: 'tx', city: 'killeen', name: 'Killeen', population: 149103 },
  { state: 'tx', city: 'waco', name: 'Waco', population: 139236 },
  { state: 'tx', city: 'denton', name: 'Denton', population: 139869 },
  { state: 'tx', city: 'midland', name: 'Midland', population: 146038 },
  { state: 'tx', city: 'round-rock', name: 'Round Rock', population: 133372 },
  { state: 'tx', city: 'the-woodlands', name: 'The Woodlands', population: 116278 },
  { state: 'tx', city: 'sugar-land', name: 'Sugar Land', population: 118488 },
  { state: 'tx', city: 'college-station', name: 'College Station', population: 120511 },
  { state: 'tx', city: 'beaumont', name: 'Beaumont', population: 115282 },
  { state: 'tx', city: 'pearland', name: 'Pearland', population: 122460 },
  { state: 'tx', city: 'richardson', name: 'Richardson', population: 121323 },
  
  // Florida (25+ cities)
  { state: 'fl', city: 'jacksonville', name: 'Jacksonville', population: 911507 },
  { state: 'fl', city: 'miami', name: 'Miami', population: 467963 },
  { state: 'fl', city: 'tampa', name: 'Tampa', population: 399700 },
  { state: 'fl', city: 'orlando', name: 'Orlando', population: 287442 },
  { state: 'fl', city: 'st-petersburg', name: 'St. Petersburg', population: 265098 },
  { state: 'fl', city: 'hialeah', name: 'Hialeah', population: 224669 },
  { state: 'fl', city: 'tallahassee', name: 'Tallahassee', population: 194500 },
  { state: 'fl', city: 'fort-lauderdale', name: 'Fort Lauderdale', population: 182437 },
  { state: 'fl', city: 'port-st-lucie', name: 'Port St. Lucie', population: 195248 },
  { state: 'fl', city: 'cape-coral', name: 'Cape Coral', population: 189633 },
  { state: 'fl', city: 'pembroke-pines', name: 'Pembroke Pines', population: 171178 },
  { state: 'fl', city: 'hollywood', name: 'Hollywood', population: 154817 },
  { state: 'fl', city: 'miramar', name: 'Miramar', population: 140328 },
  { state: 'fl', city: 'gainesville', name: 'Gainesville', population: 133997 },
  { state: 'fl', city: 'coral-springs', name: 'Coral Springs', population: 134394 },
  { state: 'fl', city: 'miami-gardens', name: 'Miami Gardens', population: 111640 },
  { state: 'fl', city: 'clearwater', name: 'Clearwater', population: 116478 },
  { state: 'fl', city: 'palm-bay', name: 'Palm Bay', population: 115552 },
  { state: 'fl', city: 'pompano-beach', name: 'Pompano Beach', population: 112046 },
  { state: 'fl', city: 'west-palm-beach', name: 'West Palm Beach', population: 111955 },
  { state: 'fl', city: 'boca-raton', name: 'Boca Raton', population: 99805 },
  { state: 'fl', city: 'naples', name: 'Naples', population: 19537 },
  { state: 'fl', city: 'sarasota', name: 'Sarasota', population: 58285 },
  { state: 'fl', city: 'fort-myers', name: 'Fort Myers', population: 87103 },
  { state: 'fl', city: 'pensacola', name: 'Pensacola', population: 54312 },
  
  // New York (20+ cities)
  { state: 'ny', city: 'new-york', name: 'New York', population: 8336817 },
  { state: 'ny', city: 'buffalo', name: 'Buffalo', population: 261310 },
  { state: 'ny', city: 'rochester', name: 'Rochester', population: 211328 },
  { state: 'ny', city: 'yonkers', name: 'Yonkers', population: 211569 },
  { state: 'ny', city: 'syracuse', name: 'Syracuse', population: 148620 },
  { state: 'ny', city: 'albany', name: 'Albany', population: 99224 },
  { state: 'ny', city: 'new-rochelle', name: 'New Rochelle', population: 79726 },
  { state: 'ny', city: 'mount-vernon', name: 'Mount Vernon', population: 68671 },
  { state: 'ny', city: 'schenectady', name: 'Schenectady', population: 67047 },
  { state: 'ny', city: 'utica', name: 'Utica', population: 65283 },
  { state: 'ny', city: 'white-plains', name: 'White Plains', population: 59559 },
  { state: 'ny', city: 'troy', name: 'Troy', population: 51401 },
  { state: 'ny', city: 'niagara-falls', name: 'Niagara Falls', population: 50193 },
  { state: 'ny', city: 'binghamton', name: 'Binghamton', population: 47969 },
  { state: 'ny', city: 'freeport', name: 'Freeport', population: 45159 },
  { state: 'ny', city: 'valley-stream', name: 'Valley Stream', population: 40659 },
  { state: 'ny', city: 'long-beach', name: 'Long Beach', population: 35029 },
  { state: 'ny', city: 'spring-valley', name: 'Spring Valley', population: 33066 },
  { state: 'ny', city: 'ithaca', name: 'Ithaca', population: 32108 },
  { state: 'ny', city: 'north-tonawanda', name: 'North Tonawanda', population: 30496 },
  
  // Pennsylvania (15+ cities)
  { state: 'pa', city: 'philadelphia', name: 'Philadelphia', population: 1584064 },
  { state: 'pa', city: 'pittsburgh', name: 'Pittsburgh', population: 302971 },
  { state: 'pa', city: 'allentown', name: 'Allentown', population: 125845 },
  { state: 'pa', city: 'erie', name: 'Erie', population: 95508 },
  { state: 'pa', city: 'reading', name: 'Reading', population: 95112 },
  { state: 'pa', city: 'scranton', name: 'Scranton', population: 76653 },
  { state: 'pa', city: 'bethlehem', name: 'Bethlehem', population: 76912 },
  { state: 'pa', city: 'lancaster', name: 'Lancaster', population: 59708 },
  { state: 'pa', city: 'harrisburg', name: 'Harrisburg', population: 50099 },
  { state: 'pa', city: 'york', name: 'York', population: 44800 },
  { state: 'pa', city: 'wilkes-barre', name: 'Wilkes-Barre', population: 44328 },
  { state: 'pa', city: 'chester', name: 'Chester', population: 32605 },
  { state: 'pa', city: 'williamsport', name: 'Williamsport', population: 27754 },
  { state: 'pa', city: 'easton', name: 'Easton', population: 28640 },
  { state: 'pa', city: 'lebanon', name: 'Lebanon', population: 26814 },
  
  // Illinois (15+ cities)
  { state: 'il', city: 'chicago', name: 'Chicago', population: 2693976 },
  { state: 'il', city: 'aurora', name: 'Aurora', population: 180542 },
  { state: 'il', city: 'rockford', name: 'Rockford', population: 148655 },
  { state: 'il', city: 'joliet', name: 'Joliet', population: 150362 },
  { state: 'il', city: 'naperville', name: 'Naperville', population: 149540 },
  { state: 'il', city: 'springfield', name: 'Springfield', population: 114230 },
  { state: 'il', city: 'peoria', name: 'Peoria', population: 113150 },
  { state: 'il', city: 'elgin', name: 'Elgin', population: 114797 },
  { state: 'il', city: 'waukegan', name: 'Waukegan', population: 87901 },
  { state: 'il', city: 'cicero', name: 'Cicero', population: 80796 },
  { state: 'il', city: 'champaign', name: 'Champaign', population: 88909 },
  { state: 'il', city: 'bloomington', name: 'Bloomington', population: 78995 },
  { state: 'il', city: 'arlington-heights', name: 'Arlington Heights', population: 77676 },
  { state: 'il', city: 'evanston', name: 'Evanston', population: 78110 },
  { state: 'il', city: 'schaumburg', name: 'Schaumburg', population: 74907 },
  
  // Ohio (15+ cities)
  { state: 'oh', city: 'columbus', name: 'Columbus', population: 898553 },
  { state: 'oh', city: 'cleveland', name: 'Cleveland', population: 381009 },
  { state: 'oh', city: 'cincinnati', name: 'Cincinnati', population: 303940 },
  { state: 'oh', city: 'toledo', name: 'Toledo', population: 272779 },
  { state: 'oh', city: 'akron', name: 'Akron', population: 190469 },
  { state: 'oh', city: 'dayton', name: 'Dayton', population: 137644 },
  { state: 'oh', city: 'parma', name: 'Parma', population: 81146 },
  { state: 'oh', city: 'canton', name: 'Canton', population: 70909 },
  { state: 'oh', city: 'youngstown', name: 'Youngstown', population: 64152 },
  { state: 'oh', city: 'lorain', name: 'Lorain', population: 65211 },
  { state: 'oh', city: 'hamilton', name: 'Hamilton', population: 63399 },
  { state: 'oh', city: 'springfield', name: 'Springfield', population: 58662 },
  { state: 'oh', city: 'kettering', name: 'Kettering', population: 57862 },
  { state: 'oh', city: 'elyria', name: 'Elyria', population: 53956 },
  { state: 'oh', city: 'lakewood', name: 'Lakewood', population: 50942 },
  
  // Georgia (10+ cities)
  { state: 'ga', city: 'atlanta', name: 'Atlanta', population: 506811 },
  { state: 'ga', city: 'augusta', name: 'Augusta', population: 202081 },
  { state: 'ga', city: 'columbus', name: 'Columbus', population: 206922 },
  { state: 'ga', city: 'macon', name: 'Macon', population: 157346 },
  { state: 'ga', city: 'savannah', name: 'Savannah', population: 147780 },
  { state: 'ga', city: 'athens', name: 'Athens', population: 127315 },
  { state: 'ga', city: 'sandy-springs', name: 'Sandy Springs', population: 108080 },
  { state: 'ga', city: 'south-fulton', name: 'South Fulton', population: 107436 },
  { state: 'ga', city: 'roswell', name: 'Roswell', population: 94763 },
  { state: 'ga', city: 'johns-creek', name: 'Johns Creek', population: 84551 },
  { state: 'ga', city: 'albany', name: 'Albany', population: 73801 },
  { state: 'ga', city: 'warner-robins', name: 'Warner Robins', population: 80308 },
  { state: 'ga', city: 'stonecrest', name: 'Stonecrest', population: 59194 },
  { state: 'ga', city: 'smyrna', name: 'Smyrna', population: 57609 },
  { state: 'ga', city: 'valdosta', name: 'Valdosta', population: 56457 },
  
  // North Carolina (10+ cities)
  { state: 'nc', city: 'charlotte', name: 'Charlotte', population: 885708 },
  { state: 'nc', city: 'raleigh', name: 'Raleigh', population: 474069 },
  { state: 'nc', city: 'greensboro', name: 'Greensboro', population: 296710 },
  { state: 'nc', city: 'durham', name: 'Durham', population: 278993 },
  { state: 'nc', city: 'winston-salem', name: 'Winston-Salem', population: 247945 },
  { state: 'nc', city: 'fayetteville', name: 'Fayetteville', population: 211657 },
  { state: 'nc', city: 'cary', name: 'Cary', population: 174721 },
  { state: 'nc', city: 'wilmington', name: 'Wilmington', population: 123744 },
  { state: 'nc', city: 'high-point', name: 'High Point', population: 114059 },
  { state: 'nc', city: 'concord', name: 'Concord', population: 96341 },
  { state: 'nc', city: 'gastonia', name: 'Gastonia', population: 80411 },
  { state: 'nc', city: 'apex', name: 'Apex', population: 58780 },
  { state: 'nc', city: 'asheville', name: 'Asheville', population: 94589 },
  { state: 'nc', city: 'chapel-hill', name: 'Chapel Hill', population: 64051 },
  
  // Michigan (10+ cities)
  { state: 'mi', city: 'detroit', name: 'Detroit', population: 639111 },
  { state: 'mi', city: 'grand-rapids', name: 'Grand Rapids', population: 198917 },
  { state: 'mi', city: 'warren', name: 'Warren', population: 139387 },
  { state: 'mi', city: 'sterling-heights', name: 'Sterling Heights', population: 134346 },
  { state: 'mi', city: 'ann-arbor', name: 'Ann Arbor', population: 123851 },
  { state: 'mi', city: 'lansing', name: 'Lansing', population: 112644 },
  { state: 'mi', city: 'dearborn', name: 'Dearborn', population: 109976 },
  { state: 'mi', city: 'livonia', name: 'Livonia', population: 95535 },
  { state: 'mi', city: 'troy', name: 'Troy', population: 87294 },
  { state: 'mi', city: 'westland', name: 'Westland', population: 84094 },
  { state: 'mi', city: 'flint', name: 'Flint', population: 81252 },
  { state: 'mi', city: 'farmington-hills', name: 'Farmington Hills', population: 83986 },
  { state: 'mi', city: 'kalamazoo', name: 'Kalamazoo', population: 76599 },
  { state: 'mi', city: 'wyoming', name: 'Wyoming', population: 76501 },
  
  // New Jersey (10+ cities)
  { state: 'nj', city: 'newark', name: 'Newark', population: 311549 },
  { state: 'nj', city: 'jersey-city', name: 'Jersey City', population: 292449 },
  { state: 'nj', city: 'paterson', name: 'Paterson', population: 159732 },
  { state: 'nj', city: 'elizabeth', name: 'Elizabeth', population: 137298 },
  { state: 'nj', city: 'lakewood', name: 'Lakewood', population: 135158 },
  { state: 'nj', city: 'edison', name: 'Edison', population: 107588 },
  { state: 'nj', city: 'woodbridge', name: 'Woodbridge', population: 103639 },
  { state: 'nj', city: 'toms-river', name: 'Toms River', population: 95438 },
  { state: 'nj', city: 'hamilton', name: 'Hamilton', population: 92297 },
  { state: 'nj', city: 'trenton', name: 'Trenton', population: 90871 },
  { state: 'nj', city: 'clifton', name: 'Clifton', population: 90296 },
  { state: 'nj', city: 'camden', name: 'Camden', population: 71791 },
  { state: 'nj', city: 'cherry-hill', name: 'Cherry Hill', population: 74553 },
  { state: 'nj', city: 'passaic', name: 'Passaic', population: 70537 },
  
  // Virginia (10+ cities)
  { state: 'va', city: 'virginia-beach', name: 'Virginia Beach', population: 459470 },
  { state: 'va', city: 'chesapeake', name: 'Chesapeake', population: 249422 },
  { state: 'va', city: 'norfolk', name: 'Norfolk', population: 230571 },
  { state: 'va', city: 'richmond', name: 'Richmond', population: 230436 },
  { state: 'va', city: 'newport-news', name: 'Newport News', population: 186247 },
  { state: 'va', city: 'alexandria', name: 'Alexandria', population: 159467 },
  { state: 'va', city: 'hampton', name: 'Hampton', population: 137148 },
  { state: 'va', city: 'roanoke', name: 'Roanoke', population: 100011 },
  { state: 'va', city: 'portsmouth', name: 'Portsmouth', population: 97915 },
  { state: 'va', city: 'suffolk', name: 'Suffolk', population: 94324 },
  { state: 'va', city: 'lynchburg', name: 'Lynchburg', population: 79009 },
  { state: 'va', city: 'harrisonburg', name: 'Harrisonburg', population: 51814 },
  { state: 'va', city: 'charlottesville', name: 'Charlottesville', population: 46553 },
  { state: 'va', city: 'danville', name: 'Danville', population: 42590 },
  
  // Washington (10+ cities)
  { state: 'wa', city: 'seattle', name: 'Seattle', population: 753675 },
  { state: 'wa', city: 'spokane', name: 'Spokane', population: 228989 },
  { state: 'wa', city: 'tacoma', name: 'Tacoma', population: 219346 },
  { state: 'wa', city: 'vancouver', name: 'Vancouver', population: 190915 },
  { state: 'wa', city: 'bellevue', name: 'Bellevue', population: 151854 },
  { state: 'wa', city: 'kent', name: 'Kent', population: 136588 },
  { state: 'wa', city: 'everett', name: 'Everett', population: 112262 },
  { state: 'wa', city: 'renton', name: 'Renton', population: 106785 },
  { state: 'wa', city: 'federal-way', name: 'Federal Way', population: 101030 },
  { state: 'wa', city: 'yakima', name: 'Yakima', population: 96968 },
  { state: 'wa', city: 'spokane-valley', name: 'Spokane Valley', population: 102976 },
  { state: 'wa', city: 'kirkland', name: 'Kirkland', population: 93010 },
  { state: 'wa', city: 'bellingham', name: 'Bellingham', population: 91482 },
  { state: 'wa', city: 'kennewick', name: 'Kennewick', population: 83921 },
  
  // Arizona (10+ cities)
  { state: 'az', city: 'phoenix', name: 'Phoenix', population: 1680992 },
  { state: 'az', city: 'tucson', name: 'Tucson', population: 548073 },
  { state: 'az', city: 'mesa', name: 'Mesa', population: 518012 },
  { state: 'az', city: 'chandler', name: 'Chandler', population: 261165 },
  { state: 'az', city: 'scottsdale', name: 'Scottsdale', population: 258069 },
  { state: 'az', city: 'glendale', name: 'Glendale', population: 252381 },
  { state: 'az', city: 'gilbert', name: 'Gilbert', population: 254114 },
  { state: 'az', city: 'tempe', name: 'Tempe', population: 195805 },
  { state: 'az', city: 'peoria', name: 'Peoria', population: 175961 },
  { state: 'az', city: 'surprise', name: 'Surprise', population: 141664 },
  { state: 'az', city: 'yuma', name: 'Yuma', population: 95548 },
  { state: 'az', city: 'avondale', name: 'Avondale', population: 89334 },
  { state: 'az', city: 'goodyear', name: 'Goodyear', population: 95294 },
  { state: 'az', city: 'flagstaff', name: 'Flagstaff', population: 75038 },
  
  // Massachusetts (10+ cities)
  { state: 'ma', city: 'boston', name: 'Boston', population: 692600 },
  { state: 'ma', city: 'worcester', name: 'Worcester', population: 206518 },
  { state: 'ma', city: 'springfield', name: 'Springfield', population: 155032 },
  { state: 'ma', city: 'cambridge', name: 'Cambridge', population: 118927 },
  { state: 'ma', city: 'lowell', name: 'Lowell', population: 115554 },
  { state: 'ma', city: 'brockton', name: 'Brockton', population: 105643 },
  { state: 'ma', city: 'new-bedford', name: 'New Bedford', population: 101079 },
  { state: 'ma', city: 'quincy', name: 'Quincy', population: 101636 },
  { state: 'ma', city: 'lynn', name: 'Lynn', population: 101253 },
  { state: 'ma', city: 'fall-river', name: 'Fall River', population: 94000 },
  { state: 'ma', city: 'newton', name: 'Newton', population: 88923 },
  { state: 'ma', city: 'lawrence', name: 'Lawrence', population: 89143 },
  { state: 'ma', city: 'somerville', name: 'Somerville', population: 81562 },
  { state: 'ma', city: 'framingham', name: 'Framingham', population: 72362 },
  
  // Tennessee (10+ cities)
  { state: 'tn', city: 'nashville', name: 'Nashville', population: 689447 },
  { state: 'tn', city: 'memphis', name: 'Memphis', population: 633104 },
  { state: 'tn', city: 'knoxville', name: 'Knoxville', population: 190740 },
  { state: 'tn', city: 'chattanooga', name: 'Chattanooga', population: 181099 },
  { state: 'tn', city: 'clarksville', name: 'Clarksville', population: 166722 },
  { state: 'tn', city: 'murfreesboro', name: 'Murfreesboro', population: 152769 },
  { state: 'tn', city: 'franklin', name: 'Franklin', population: 87394 },
  { state: 'tn', city: 'jackson', name: 'Jackson', population: 68205 },
  { state: 'tn', city: 'johnson-city', name: 'Johnson City', population: 71046 },
  { state: 'tn', city: 'bartlett', name: 'Bartlett', population: 54613 },
  { state: 'tn', city: 'hendersonville', name: 'Hendersonville', population: 61753 },
  { state: 'tn', city: 'kingsport', name: 'Kingsport', population: 54127 },
  { state: 'tn', city: 'collierville', name: 'Collierville', population: 51324 },
  { state: 'tn', city: 'smyrna', name: 'Smyrna', population: 53070 },
  
  // Colorado (10+ cities)
  { state: 'co', city: 'denver', name: 'Denver', population: 727211 },
  { state: 'co', city: 'colorado-springs', name: 'Colorado Springs', population: 500130 },
  { state: 'co', city: 'aurora', name: 'Aurora', population: 386261 },
  { state: 'co', city: 'fort-collins', name: 'Fort Collins', population: 169810 },
  { state: 'co', city: 'lakewood', name: 'Lakewood', population: 155733 },
  { state: 'co', city: 'thornton', name: 'Thornton', population: 141867 },
  { state: 'co', city: 'arvada', name: 'Arvada', population: 124402 },
  { state: 'co', city: 'westminster', name: 'Westminster', population: 116317 },
  { state: 'co', city: 'pueblo', name: 'Pueblo', population: 111876 },
  { state: 'co', city: 'centennial', name: 'Centennial', population: 108418 },
  { state: 'co', city: 'boulder', name: 'Boulder', population: 108250 },
  { state: 'co', city: 'greeley', name: 'Greeley', population: 108795 },
  { state: 'co', city: 'longmont', name: 'Longmont', population: 98885 },
  { state: 'co', city: 'loveland', name: 'Loveland', population: 78877 },
  
  // Maryland (10 cities)
  { state: 'md', city: 'baltimore', name: 'Baltimore', population: 593490 },
  { state: 'md', city: 'frederick', name: 'Frederick', population: 78171 },
  { state: 'md', city: 'gaithersburg', name: 'Gaithersburg', population: 69657 },
  { state: 'md', city: 'rockville', name: 'Rockville', population: 67117 },
  { state: 'md', city: 'bowie', name: 'Bowie', population: 58681 },
  { state: 'md', city: 'hagerstown', name: 'Hagerstown', population: 43527 },
  { state: 'md', city: 'annapolis', name: 'Annapolis', population: 40812 },
  { state: 'md', city: 'college-park', name: 'College Park', population: 34740 },
  { state: 'md', city: 'salisbury', name: 'Salisbury', population: 33050 },
  { state: 'md', city: 'laurel', name: 'Laurel', population: 29699 },
  
  // Indiana (10 cities)
  { state: 'in', city: 'indianapolis', name: 'Indianapolis', population: 887642 },
  { state: 'in', city: 'fort-wayne', name: 'Fort Wayne', population: 270402 },
  { state: 'in', city: 'evansville', name: 'Evansville', population: 117298 },
  { state: 'in', city: 'south-bend', name: 'South Bend', population: 103453 },
  { state: 'in', city: 'carmel', name: 'Carmel', population: 101068 },
  { state: 'in', city: 'fishers', name: 'Fishers', population: 98977 },
  { state: 'in', city: 'bloomington', name: 'Bloomington', population: 79168 },
  { state: 'in', city: 'hammond', name: 'Hammond', population: 77879 },
  { state: 'in', city: 'gary', name: 'Gary', population: 69093 },
  { state: 'in', city: 'lafayette', name: 'Lafayette', population: 70783 },
  
  // Missouri (10 cities)
  { state: 'mo', city: 'kansas-city', name: 'Kansas City', population: 508090 },
  { state: 'mo', city: 'st-louis', name: 'St. Louis', population: 301578 },
  { state: 'mo', city: 'springfield', name: 'Springfield', population: 169176 },
  { state: 'mo', city: 'columbia', name: 'Columbia', population: 126254 },
  { state: 'mo', city: 'independence', name: 'Independence', population: 123011 },
  { state: 'mo', city: 'lee-summit', name: "Lee's Summit", population: 101108 },
  { state: 'mo', city: 'ofallon', name: "O'Fallon", population: 91316 },
  { state: 'mo', city: 'st-joseph', name: 'St. Joseph', population: 72473 },
  { state: 'mo', city: 'st-charles', name: 'St. Charles', population: 71028 },
  { state: 'mo', city: 'blue-springs', name: 'Blue Springs', population: 58604 },
  
  // Wisconsin (10 cities)
  { state: 'wi', city: 'milwaukee', name: 'Milwaukee', population: 577222 },
  { state: 'wi', city: 'madison', name: 'Madison', population: 269840 },
  { state: 'wi', city: 'green-bay', name: 'Green Bay', population: 107395 },
  { state: 'wi', city: 'kenosha', name: 'Kenosha', population: 100150 },
  { state: 'wi', city: 'racine', name: 'Racine', population: 76893 },
  { state: 'wi', city: 'appleton', name: 'Appleton', population: 75644 },
  { state: 'wi', city: 'waukesha', name: 'Waukesha', population: 71158 },
  { state: 'wi', city: 'oshkosh', name: 'Oshkosh', population: 66753 },
  { state: 'wi', city: 'eau-claire', name: 'Eau Claire', population: 69421 },
  { state: 'wi', city: 'janesville', name: 'Janesville', population: 65615 },
  
  // Minnesota (10 cities)
  { state: 'mn', city: 'minneapolis', name: 'Minneapolis', population: 429954 },
  { state: 'mn', city: 'st-paul', name: 'St. Paul', population: 311527 },
  { state: 'mn', city: 'rochester', name: 'Rochester', population: 121395 },
  { state: 'mn', city: 'bloomington', name: 'Bloomington', population: 89987 },
  { state: 'mn', city: 'duluth', name: 'Duluth', population: 86697 },
  { state: 'mn', city: 'st-cloud', name: 'St. Cloud', population: 68881 },
  { state: 'mn', city: 'eden-prairie', name: 'Eden Prairie', population: 64198 },
  { state: 'mn', city: 'burnsville', name: 'Burnsville', population: 64317 },
  { state: 'mn', city: 'blaine', name: 'Blaine', population: 70222 },
  { state: 'mn', city: 'lakeville', name: 'Lakeville', population: 69490 },
  
  // South Carolina (10 cities)
  { state: 'sc', city: 'charleston', name: 'Charleston', population: 150227 },
  { state: 'sc', city: 'columbia', name: 'Columbia', population: 136632 },
  { state: 'sc', city: 'north-charleston', name: 'North Charleston', population: 114852 },
  { state: 'sc', city: 'mount-pleasant', name: 'Mount Pleasant', population: 90801 },
  { state: 'sc', city: 'rock-hill', name: 'Rock Hill', population: 74410 },
  { state: 'sc', city: 'greenville', name: 'Greenville', population: 70635 },
  { state: 'sc', city: 'summerville', name: 'Summerville', population: 50915 },
  { state: 'sc', city: 'goose-creek', name: 'Goose Creek', population: 45946 },
  { state: 'sc', city: 'hilton-head-island', name: 'Hilton Head Island', population: 37661 },
  { state: 'sc', city: 'florence', name: 'Florence', population: 37417 },
  
  // Alabama (10 cities)
  { state: 'al', city: 'birmingham', name: 'Birmingham', population: 200733 },
  { state: 'al', city: 'montgomery', name: 'Montgomery', population: 200603 },
  { state: 'al', city: 'huntsville', name: 'Huntsville', population: 215006 },
  { state: 'al', city: 'mobile', name: 'Mobile', population: 187041 },
  { state: 'al', city: 'tuscaloosa', name: 'Tuscaloosa', population: 101129 },
  { state: 'al', city: 'hoover', name: 'Hoover', population: 92606 },
  { state: 'al', city: 'dothan', name: 'Dothan', population: 71072 },
  { state: 'al', city: 'auburn', name: 'Auburn', population: 76143 },
  { state: 'al', city: 'decatur', name: 'Decatur', population: 57938 },
  { state: 'al', city: 'madison', name: 'Madison', population: 56933 },
  
  // Louisiana (10 cities)
  { state: 'la', city: 'new-orleans', name: 'New Orleans', population: 383997 },
  { state: 'la', city: 'baton-rouge', name: 'Baton Rouge', population: 227470 },
  { state: 'la', city: 'shreveport', name: 'Shreveport', population: 187593 },
  { state: 'la', city: 'metairie', name: 'Metairie', population: 143507 },
  { state: 'la', city: 'lafayette', name: 'Lafayette', population: 121374 },
  { state: 'la', city: 'lake-charles', name: 'Lake Charles', population: 84872 },
  { state: 'la', city: 'kenner', name: 'Kenner', population: 64364 },
  { state: 'la', city: 'bossier-city', name: 'Bossier City', population: 62701 },
  { state: 'la', city: 'monroe', name: 'Monroe', population: 47702 },
  { state: 'la', city: 'alexandria', name: 'Alexandria', population: 45275 },
  
  // Kentucky (10 cities)
  { state: 'ky', city: 'louisville', name: 'Louisville', population: 633045 },
  { state: 'ky', city: 'lexington', name: 'Lexington', population: 322570 },
  { state: 'ky', city: 'bowling-green', name: 'Bowling Green', population: 72294 },
  { state: 'ky', city: 'owensboro', name: 'Owensboro', population: 60183 },
  { state: 'ky', city: 'covington', name: 'Covington', population: 40455 },
  { state: 'ky', city: 'hopkinsville', name: 'Hopkinsville', population: 30089 },
  { state: 'ky', city: 'richmond', name: 'Richmond', population: 36157 },
  { state: 'ky', city: 'florence', name: 'Florence', population: 31946 },
  { state: 'ky', city: 'georgetown', name: 'Georgetown', population: 37086 },
  { state: 'ky', city: 'elizabethtown', name: 'Elizabethtown', population: 31394 },
  
  // Oregon (10 cities)
  { state: 'or', city: 'portland', name: 'Portland', population: 652503 },
  { state: 'or', city: 'eugene', name: 'Eugene', population: 176654 },
  { state: 'or', city: 'salem', name: 'Salem', population: 177432 },
  { state: 'or', city: 'gresham', name: 'Gresham', population: 114247 },
  { state: 'or', city: 'hillsboro', name: 'Hillsboro', population: 109128 },
  { state: 'or', city: 'beaverton', name: 'Beaverton', population: 99037 },
  { state: 'or', city: 'bend', name: 'Bend', population: 100421 },
  { state: 'or', city: 'medford', name: 'Medford', population: 85824 },
  { state: 'or', city: 'springfield', name: 'Springfield', population: 62256 },
  { state: 'or', city: 'corvallis', name: 'Corvallis', population: 59922 },
  
  // Oklahoma (10 cities)
  { state: 'ok', city: 'oklahoma-city', name: 'Oklahoma City', population: 695000 },
  { state: 'ok', city: 'tulsa', name: 'Tulsa', population: 413066 },
  { state: 'ok', city: 'norman', name: 'Norman', population: 128026 },
  { state: 'ok', city: 'broken-arrow', name: 'Broken Arrow', population: 113540 },
  { state: 'ok', city: 'edmond', name: 'Edmond', population: 94428 },
  { state: 'ok', city: 'moore', name: 'Moore', population: 62793 },
  { state: 'ok', city: 'midwest-city', name: 'Midwest City', population: 58409 },
  { state: 'ok', city: 'enid', name: 'Enid', population: 51308 },
  { state: 'ok', city: 'stillwater', name: 'Stillwater', population: 48394 },
  { state: 'ok', city: 'muskogee', name: 'Muskogee', population: 36878 },
  
  // Connecticut (10 cities)
  { state: 'ct', city: 'bridgeport', name: 'Bridgeport', population: 148654 },
  { state: 'ct', city: 'new-haven', name: 'New Haven', population: 134023 },
  { state: 'ct', city: 'hartford', name: 'Hartford', population: 121054 },
  { state: 'ct', city: 'stamford', name: 'Stamford', population: 135470 },
  { state: 'ct', city: 'waterbury', name: 'Waterbury', population: 114403 },
  { state: 'ct', city: 'norwalk', name: 'Norwalk', population: 91184 },
  { state: 'ct', city: 'danbury', name: 'Danbury', population: 86518 },
  { state: 'ct', city: 'new-britain', name: 'New Britain', population: 74135 },
  { state: 'ct', city: 'west-hartford', name: 'West Hartford', population: 64083 },
  { state: 'ct', city: 'greenwich', name: 'Greenwich', population: 63518 },
  
  // Kansas (5 cities)
  { state: 'ks', city: 'wichita', name: 'Wichita', population: 397532 },
  { state: 'ks', city: 'overland-park', name: 'Overland Park', population: 197238 },
  { state: 'ks', city: 'kansas-city', name: 'Kansas City', population: 156607 },
  { state: 'ks', city: 'olathe', name: 'Olathe', population: 141290 },
  { state: 'ks', city: 'topeka', name: 'Topeka', population: 125310 },
  
  // Utah (5 cities)
  { state: 'ut', city: 'salt-lake-city', name: 'Salt Lake City', population: 200133 },
  { state: 'ut', city: 'west-valley-city', name: 'West Valley City', population: 140230 },
  { state: 'ut', city: 'west-jordan', name: 'West Jordan', population: 116961 },
  { state: 'ut', city: 'provo', name: 'Provo', population: 115162 },
  { state: 'ut', city: 'sandy', name: 'Sandy', population: 96904 },
  
  // Nevada (5 cities)
  { state: 'nv', city: 'las-vegas', name: 'Las Vegas', population: 641903 },
  { state: 'nv', city: 'henderson', name: 'Henderson', population: 320189 },
  { state: 'nv', city: 'reno', name: 'Reno', population: 264165 },
  { state: 'nv', city: 'north-las-vegas', name: 'North Las Vegas', population: 262527 },
  { state: 'nv', city: 'sparks', name: 'Sparks', population: 108445 },
  
  // Arkansas (5 cities)
  { state: 'ar', city: 'little-rock', name: 'Little Rock', population: 198606 },
  { state: 'ar', city: 'fort-smith', name: 'Fort Smith', population: 89142 },
  { state: 'ar', city: 'fayetteville', name: 'Fayetteville', population: 93949 },
  { state: 'ar', city: 'springdale', name: 'Springdale', population: 87619 },
  { state: 'ar', city: 'jonesboro', name: 'Jonesboro', population: 78576 },
  
  // Iowa (5 cities)
  { state: 'ia', city: 'des-moines', name: 'Des Moines', population: 214133 },
  { state: 'ia', city: 'cedar-rapids', name: 'Cedar Rapids', population: 137710 },
  { state: 'ia', city: 'davenport', name: 'Davenport', population: 101724 },
  { state: 'ia', city: 'sioux-city', name: 'Sioux City', population: 85797 },
  { state: 'ia', city: 'iowa-city', name: 'Iowa City', population: 74828 },
  
  // Mississippi (5 cities)
  { state: 'ms', city: 'jackson', name: 'Jackson', population: 153701 },
  { state: 'ms', city: 'gulfport', name: 'Gulfport', population: 72926 },
  { state: 'ms', city: 'southaven', name: 'Southaven', population: 54648 },
  { state: 'ms', city: 'biloxi', name: 'Biloxi', population: 49449 },
  { state: 'ms', city: 'hattiesburg', name: 'Hattiesburg', population: 48730 },
  
  // Additional cities to reach 500+
  { state: 'ne', city: 'omaha', name: 'Omaha', population: 486051 },
  { state: 'ne', city: 'lincoln', name: 'Lincoln', population: 295618 },
  { state: 'nm', city: 'albuquerque', name: 'Albuquerque', population: 564559 },
  { state: 'nm', city: 'las-cruces', name: 'Las Cruces', population: 111385 },
  { state: 'wv', city: 'charleston', name: 'Charleston', population: 46536 },
  { state: 'wv', city: 'huntington', name: 'Huntington', population: 45110 },
  { state: 'nh', city: 'manchester', name: 'Manchester', population: 115644 },
  { state: 'nh', city: 'nashua', name: 'Nashua', population: 91322 },
  { state: 'me', city: 'portland', name: 'Portland', population: 68408 },
  { state: 'me', city: 'lewiston', name: 'Lewiston', population: 37121 },
  { state: 'id', city: 'boise', name: 'Boise', population: 235684 },
  { state: 'id', city: 'meridian', name: 'Meridian', population: 117635 },
  { state: 'hi', city: 'honolulu', name: 'Honolulu', population: 345064 },
  { state: 'hi', city: 'pearl-city', name: 'Pearl City', population: 47698 },
  { state: 'ri', city: 'providence', name: 'Providence', population: 190934 },
  { state: 'ri', city: 'warwick', name: 'Warwick', population: 82823 },
  { state: 'mt', city: 'billings', name: 'Billings', population: 117116 },
  { state: 'mt', city: 'missoula', name: 'Missoula', population: 75516 },
  { state: 'de', city: 'wilmington', name: 'Wilmington', population: 70898 },
  { state: 'de', city: 'dover', name: 'Dover', population: 39403 },
  { state: 'sd', city: 'sioux-falls', name: 'Sioux Falls', population: 192517 },
  { state: 'sd', city: 'rapid-city', name: 'Rapid City', population: 74703 },
  { state: 'nd', city: 'fargo', name: 'Fargo', population: 125990 },
  { state: 'nd', city: 'bismarck', name: 'Bismarck', population: 73622 },
  { state: 'ak', city: 'anchorage', name: 'Anchorage', population: 291247 },
  { state: 'ak', city: 'fairbanks', name: 'Fairbanks', population: 32711 },
  { state: 'vt', city: 'burlington', name: 'Burlington', population: 44743 },
  { state: 'vt', city: 'south-burlington', name: 'South Burlington', population: 20292 },
  { state: 'wy', city: 'cheyenne', name: 'Cheyenne', population: 65132 },
  { state: 'wy', city: 'casper', name: 'Casper', population: 59038 },
];

// Get cities by state
export function getCitiesByState(stateCode: string): typeof US_MAJOR_CITIES {
  return US_MAJOR_CITIES.filter(city => city.state === stateCode.toLowerCase());
}

// Get top cities (for sitemap)
export function getTopCities(limit: number = 100): typeof US_MAJOR_CITIES {
  return US_MAJOR_CITIES
    .sort((a, b) => b.population - a.population)
    .slice(0, limit);
}